### ISSUE TITLE
大佬，我想问下你的 markdown 图床用的谁家的？哈哈

### ISSUE THREAD

**Issue by JKAK47** [ZhongFuCheng3y/3y#1]
我看你引用的图片链接  域名是：user-gold-cdn.xitu.io 是自己搭建的吗？

**Comment by ZhongFuCheng3y** [comment]
> 我看你引用的图片链接 域名是：user-gold-cdn.xitu.io 是自己搭建的吗？

不是不是，复制到掘金，然后再复制过来的。

**Comment by chem2code** [comment]
从关注公众号到github了，未来的大牛 哈哈

**Comment by vivitrip** [comment]
图床，每一个md爱好者必须要考虑的问题

**Comment by tanjuntao** [comment]
> > 我看你引用的图片链接 域名是：user-gold-cdn.xitu.io 是自己搭建的吗？
> 
> 不是不是，复制到掘金，然后再复制过来的。

有个小疑问，在 repo 当中建立一个文件夹专门存放图片，然后在 markdown 中引用图片，这种做法不推荐吗？
