### ISSUE TITLE
腾讯一年快到期了  没想到阿里对新用户这么照顾

### ISSUE THREAD

**Issue by deepjava-gm** [ZhongFuCheng3y/3y#6]
![image](https://user-images.githubusercontent.com/34341760/70162245-4dbaa700-16f8-11ea-9a02-4e2ebe9dcd62.png)

**Comment by ZhongFuCheng3y** [comment]
哪家都是对新用户 友好的。。

**Comment by deepjava-gm** [comment]
腾讯当初是10块钱一个月，这阿里新用户10块一个月都不到 的确很划算 打算用朋友手机号入手一年 哈哈

**Comment by EdwardCooler** [comment]
润哥说他已收到你的来信，并推了一下他的隐形眼镜
